version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4

jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          command: |
            go test -v

  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          command: |
            gcloud --quiet app deploy app.yaml

workflows:
  version: 2
  build:
    jobs:
      - test
  deploy:
    jobs:
      - deploy
