version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4

jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest

    steps:
      - checkout
      - gcp-cli/initialize # stepsで使うにはgcp-cli./initializeが必要
      - run:
          name: Deploy Go Web Server to GAE
          command: |
            gcloud --quiet app deploy app.yaml

workflows:
  version: 2
  deploy:
    jobs:
      - build
